# Site info
title: matthew's website
author:
    name: Matthew Janssen

# build info
theme: minima

# config
header_pages:
- films.md
- books.md
- games.md

collections:

    books:
      output: true
      permalink: /books/:path/

    films:
      output: true
      permalink: /films/:path/

    games:
      output: true
      permalink: /games/:path/