baseURL = 'https://matthewjanssen.org/'
languageCode = 'en-us'
title = "Matthew's Website"
theme = 'hugo-bearblog'

disableKinds = ['rss']

titleCaseStyle = 'none'

[taxonomies]
  book = 'books'
  comic = 'comics'
  film = 'films'
  graphic-novel = 'graphic-novels'
  live-theatre = 'live-theatre'
  manga = 'manga'
  tv-series = 'tv-series'
  video-game = 'video-games'

# hugo-bearblog config
[params]
  hideMadeWithLine = true